### PR TITLE
Apply fixes for 0.0.28 (up to 0.0.42)

### PR DESCRIPTION
**Pull request by bddvlpr**
I do not take credit for these changes. Big thanks to Ennea for updating the preload location. See #26.
(Uses perl instead of sed now).
Tested on both MacOS and NixOS.

### CODE REVIEW

**Comment by bddvlpr** [comment]
For NixOS users:
```nix
package = pkgs.discocss.overrideAttrs (old: rec {
      version = "0.3.0";
      src = pkgs.fetchFromGitHub {
        owner = "bddvlpr";
        repo = "discocss";
        rev = "v${version}";
        hash = "sha256-2K7SPTvORzgZ1ZiCtS5TOShuAnmtI5NYkdQPRXIBP/I=";
      };
    });
```

**Comment by aspauldingcode** [comment]
@bddvlpr  can we get an updated patch for nixos users on discord 0.0.42?

**Comment by bddvlpr** [comment]
While I switched to Vencord a while ago, this patch still works and the bootstrap file has not changed significantly to render this broken. Use the override on the discocss module above to actually use it though. The default discocss package in nixpkgs is currently the old broken one.

image

**Comment by Weathercold** [comment]
v3.0.1 doesn't work on 0.0.49

**Pull request closed without merging**
